from flua.Tools.IDE.Widgets.BPConsoleWidget import *
from flua.Tools.IDE.Widgets.BPMessageView import *
from flua.Tools.IDE.Widgets.BPDependencyView import *
from flua.Tools.IDE.Widgets.BPFileBrowser import *
from flua.Tools.IDE.Widgets.BPModuleBrowser import *
from flua.Tools.IDE.Widgets.BPScribbleWidget import *
from flua.Tools.IDE.Widgets.BPWorkspacesView import *
from flua.Tools.IDE.Widgets.BPWorkspace import *
from flua.Tools.IDE.Widgets.BPMetaDataWidget import *
from flua.Tools.IDE.Widgets.BPOutlineView import *
from flua.Tools.IDE.Widgets.BPSearchEdit import *
from flua.Tools.IDE.Widgets.BPReplaceEdit import *
from flua.Tools.IDE.Widgets.BPSearchResultsWidget import *
from flua.Tools.IDE.Widgets.BPCommandEdit import *
from flua.Tools.IDE.Widgets.BPChatWidget import *
from flua.Tools.IDE.Widgets.BPDocNavigator import *
from flua.Tools.IDE.Widgets.BPDebugger import *
