from bp.Tools.IDE.Widgets.BPConsoleWidget import *
from bp.Tools.IDE.Widgets.BPMessageView import *
from bp.Tools.IDE.Widgets.BPDependencyView import *
from bp.Tools.IDE.Widgets.BPFileBrowser import *
from bp.Tools.IDE.Widgets.BPModuleBrowser import *
from bp.Tools.IDE.Widgets.BPScribbleWidget import *
from bp.Tools.IDE.Widgets.BPWorkspacesView import *
from bp.Tools.IDE.Widgets.BPWorkspace import *
from bp.Tools.IDE.Widgets.BPMetaDataWidget import *
from bp.Tools.IDE.Widgets.BPOutlineView import *
from bp.Tools.IDE.Widgets.BPSearchEdit import *
#from bp.Tools.IDE.Widgets.BPIntelliView import *
